# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: Docker CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build docker image
        working-directory: udagram-frontend
        run: docker build . --file Dockerfile --tag udagram-frontend
